### PR TITLE
:bug: Set xmx value on JVM to avoid OOMKilled

### LINKED ISSUE #340: Allow setting -Xmx value on JDTLS
See https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/745#issuecomment-856821942

### LINKED ISSUE #386: Increase verbosity level of a log line that prints java symbols
https://github.com/konveyor/analyzer-lsp/blob/ec501b3f8f4af1d304ceb0432eb059a80f5015b3/provider/internal/java/service_client.go#L53

### PR DESCRIPTION
**Pull request by pranavgaikwad**
Fixes #340 
Fixes #386

### CODE REVIEW

**Review by djzager — APPROVED** [review]

**Review by shawn-hurley — APPROVED** [review]

File: engine/engine.go [hunk 1]
```diff
@@ -425,7 +425,7 @@ func (r *ruleEngine) createViolation(ctx context.Context, conditionResponse Cond
 			for scanner.Scan() {
 				if incident.LineNumber != nil && strings.HasPrefix(strings.TrimSpace(scanner.Text()), fmt.Sprintf("%v", *incident.LineNumber)) {
 					originalCodeSnip = strings.TrimSpace(re.ReplaceAllString(scanner.Text(), "$2"))
-					r.logger.Info("found orignalCodeSnip", "lineNuber", incident.LineNumber, "orignal", originalCodeSnip)
+					r.logger.V(5).Info("found originalCodeSnip", "lineNuber", incident.LineNumber, "original", originalCodeSnip)
```
Comment (shawn-hurley) [inline engine/engine.go:428]: nice, I can't spell!

**Review by shawn-hurley — APPROVED** [review]
