### PR TITLE
:bug: fix dependencies for binaries

### LINKED ISSUE #237: Running dependency CLI with binaries fails
It looks like we need properly implement dependency CLI to handle binaries. When a binary is used with the dep command, we see following error:

```
[CMD] Running: /usr/bin/konveyor-analyzer-dep --provider-settings /addon/opt/settings.json --output-file /addon/deps.yaml",
"[CMD] failed: exit status 1.",
"> time=\"2023-06-28T19:54:15Z\" level=error msg=\"grpc unable to get info\" error=\"rpc error: code = Unavailable desc = connection error: desc = \\\"transport: Error while dialing: dial tcp 127.0.0.1:35491: connect: connection refused\\\"\" provider=grpc",
"> time=\"2023-06-28T19:54:20Z\" level=error msg=\"failed to get list of dependencies for provider\" error=\"exit status 1\" provider=go",
"> time=\"2023-06-28T19:54:23Z\" level=error msg=\"failed to get list of dependencies for provider\" error=\"open /addon/bin/com-redhat-ceylon-model-1-3-3-jar-decompiled/pom.xml: no such file or directory\" provider=java",
"> time=\"2023-06-28T19:54:23Z\" level=info msg=\"provider does not have dependency capability\" provider=builtin",
"> time=\"2023-06-28T19:54:23Z\" level=info msg=\"failed to get dependencies from all given providers\"",
"> "
```

Maven artifact used in above test comes from:

```
    <groupId>org.ceylon-lang</groupId>
    <artifactId>com.redhat.ceylon.model</artifactId>
    <version>1.3.3</version>
```

### PR DESCRIPTION
**Pull request by pranavgaikwad**
Fixes #237

### CODE REVIEW

File: provider/internal/java/util.go [hunk 1]
```diff
@@ -97,7 +97,7 @@ func decompile(ctx context.Context, log logr.Logger, archivePath, projectPath st
 		}
 
 		if f.FileInfo().IsDir() {
-			os.MkdirAll(filePath, f.Mode())
+			os.MkdirAll(filePath, f.Mode()|0111)
```
Comment (shawn-hurley) [inline provider/internal/java/util.go:100]: Confused on the or mode here

File: provider/internal/java/dependency.go [hunk 2]
```diff
@@ -39,14 +40,25 @@ func (p *javaServiceClient) findPom() string {
...
+	var err error
+	var ll map[uri.URI][]konveyor.DepDAGItem
 	m := map[uri.URI][]*provider.Dep{}
+	if p.isLocationBinary {
+		ll = make(map[uri.URI][]konveyor.DepDAGItem, 0)
+		// for binaries we only find JARs embedded in archive
+		w := walker{
+			deps: ll,
+		}
+		filepath.WalkDir(p.config.DependencyPath, w.walkDirForJar)
```
Comment (shawn-hurley) [inline provider/internal/java/dependency.go:52]: I think we use this code somewhere else too right? I wonder if it could always be used here only and then added to out of the others if not binary so we only do this code in one place?

**Review by shawn-hurley — APPROVED** [review]
Overall looks good, just a couple of questions
