### PR TITLE
:bug: fixing logs with new command format, adding new format to dep command

### LINKED ISSUE #453: :bug: Analyzer-lsp should exit != 0 when an unknown option is passed.
This will prevent silent failures when used programmatically due to integration issues.

### PR DESCRIPTION
**Pull request by shawn-hurley**
fixes #453

### CODE REVIEW

File: cmd/dep/main.go [hunk 1]
```diff
@@ -23,173 +24,186 @@ var (
...
-	if err != nil {
-		errLog.Error(err, "failed to validate input flags")
-		os.Exit(1)
-	}
+func DependencyCmd() *cobra.Command {
+
+	var errLog logr.Logger
+	rootCmd := &cobra.Command{
+		Use:   "konveyor-analyzer-dep",
+		Short: "Tool for working with dependency for konveyor-analyzer",
```
Comment (eemcmullan) [inline cmd/dep/main.go:37]: I feel like this description could be worded differently, but nothing major. Otherwise LGTM

**Review by eemcmullan — APPROVED** [review]

**Review by pranavgaikwad — APPROVED** [review]

File: cmd/dep/main.go (hunk 1 above)
Comment (shawn-hurley) [reply cmd/dep/main.go]: updated

**Review by eemcmullan — APPROVED** [review]
