### PR TITLE
:bug: Fix compile step

### LINKED ISSUE #393: [BUG] Java / Maven analysis does not work if the project does not compile with JDK 17
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

60c4fcbe62658708fb4290cbdcb24b75e9619814

### Priority

Blocker

### Current Behavior

If a Maven project does not compile with JDK 17, the analysis will abort.

### Expected Behavior

Make it work with misc. Java / JDK versions. Perhaps some hint for the desired Java version is necessary?

### How Reproducible

Always (Default)

### Steps To Reproduce

Project which is incompatible with JDK 17 needed, e.g., by calling `sun.misc.Unsafe`

### Environment

_No response_

### Anything else?

If the call to Maven fails, it would be great to get the (full) output of the background process for failure analysis.

### PR DESCRIPTION
**Pull request by jmle**
Fixes #393 

Remove "compile" goal from maven invocations, as some applications may not be compilable with the JDK version we bundle.

Related to https://github.com/konveyor/analyzer-lsp/issues/393 and https://github.com/konveyor/analyzer-lsp/issues/393

### CODE REVIEW

File: provider/internal/java/dependency.go [hunk 1]
```diff
@@ -180,18 +180,10 @@ func (p *javaServiceClient) GetDependenciesDAG(ctx context.Context) (map[uri.URI
 
 	moddir := filepath.Dir(path)
 
-	pom, err := gopom.Parse(path)
```
Comment (shawn-hurley) [inline provider/internal/java/dependency.go:183]: Does this remove that dep too?

**Comment by shawn-hurley** [comment]
Do we have a multi-module test case yet? I would love to see that added with/ this change to make sure we don't break that in the future (I am worried about me breaking it :) )

File: provider/internal/java/dependency.go (hunk 1 above)
Comment (pranavgaikwad) [reply provider/internal/java/dependency.go:183]: think its still used in fallback

**Review by pranavgaikwad — COMMENTED** [review]
Does this completely fix #392?

**Comment by pranavgaikwad** [comment]
> Do we have a multi-module test case yet? I would love to see that added with/ this change to make sure we don't break that in the future (I am worried about me breaking it :) )

Captured in issue here, will add sometime this week https://github.com/konveyor/analyzer-lsp/issues/399

**Comment by ascheman** [comment]
> Do we have a multi-module test case yet? I would love to see that added with/ this change to make sure we don't break that in the future (I am worried about me breaking it :) )

If it helps: The problem came up in my (company project) multi project build. Tested the patch with that project already.

**Review by pranavgaikwad — APPROVED** [review]

File: provider/internal/java/dependency.go (hunk 1 above)
Comment (jmle) [reply provider/internal/java/dependency.go:183]: Yep, still used somewhere else

**Comment by ascheman** [comment]
Thanks!
