### PR TITLE
:bug: adding back off handler and using it for the java

### LINKED ISSUE #147: Error causes tight endless loop.
```
sh-5.1# /addon/opt/konveyor-analyzer --provider-settings /addon/opt/settings.yaml --output-file /addon/report.yaml --rules /addon/rules/bundles/12/rulesets/16-rule-example.yaml   | more
time="2023-05-15T18:18:18Z" level=error msg="unable to load rule set" error="stat /addon/rules/bundles/12/rulesets/ruleset.yaml: no such file or directory" logger=parser
time="2023-05-15T18:18:18Z" level=unknown msg="starting to run rpc connection" provider=java
here cmd failed- fork/exec /addon/opt/jdtls/bin/jdtls: no such file or directorytime="2023-05-15T18:18:18Z" level=error msg="initialize failed" error="write |1: file alread
y closed" provider=java
time="2023-05-15T18:18:18Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:18Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:18Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:18Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:18Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:18Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:18Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:18Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:18Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:18Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:18Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:18Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:19Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:19Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:19Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:19Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
time="2023-05-15T18:18:19Z" level=error msg="initialize failed" error="write |1: file already closed" provider=java
...

sh-5.1# ls -Fal /addon/rules/bundles/12/rulesets/16-rule-example.yaml
-rw-rw-rw-. 1 root root 3255 May 15 18:17 /addon/rules/bundles/12/rulesets/16-rule-example.yaml
sh-5.1# cat opt/settings.yaml 
- name: go
  location: /addon/source/sample
  binaryLocation: /addon/opt/gopls
- name: java
  location: /addon/source/sample
  binaryLocation: /addon/opt/jdtls/bin/jdtls
  providerSpecificConfig:
    bindles: /addon/opt/java-analyzer-bundle.jar
- name: builtin
  location: /addon/source/sample

```

### PR DESCRIPTION
**Pull request by shawn-hurley**
fixes #147 

Adding back off to failed requests handler for the jsonrpc. This will be usable once we convert to use the correct library.

### CODE REVIEW

File: jsonrpc2/backoff_handler.go [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+
+	d := backOff.BackoffRequest()
+	b.logger.V(5).Info("starting backing off request", "method", r.Method, "duration", d)
+	time.Sleep(d)
+	b.logger.V(5).Info("stoping backing off request", "method", r.Method)
+	return context.WithValue(ctx, "back-off-timer", requestKey)
+}
+
+// Response is called near the start of processing any response.
+func (b *BackoffHandler) Response(ctx context.Context, conn *Conn, direction Direction, r *WireResponse) context.Context {
```
Comment (fabianvf) [inline jsonrpc2/backoff_handler.go:115]: I'm a little confused by these just returning context

File: jsonrpc2/backoff_handler.go [hunk 2]
```diff
@@ -0,0 +1,154 @@
...
+}
+
+// Read is called with a count each time some data is read from the stream.
+// The read calls are delayed until after the data has been interpreted so
+// that it can be attributed to a request/response.
+func (b *BackoffHandler) Read(ctx context.Context, bytes int64) context.Context {
+	return ctx
+}
+
+// Wrote is called each time some data is written to the stream.
```
Comment (fabianvf) [inline jsonrpc2/backoff_handler.go:145]: I assume these are supposed to be `Write`?

```suggestion
// Write is called each time some data is written to the stream.
```

File: jsonrpc2/backoff_handler.go (hunk 1 above)
Comment (shawn-hurley) [reply jsonrpc2/backoff_handler.go:115]: And why are we only returning errors because we have to be apart of the interface https://github.com/konveyor/analyzer-lsp/blob/main/jsonrpc2/handler.go#L13

And we learned that there is an updated lsp from go so that we don't have to copy, and it has the same interface so we are able to use this, once we use the correct library.

Comment (shawn-hurley) [reply jsonrpc2/backoff_handler.go:115]: I just looked this up, and apparently, the interface is different: https://pkg.go.dev/go.lsp.dev/jsonrpc2#Handler

It does not allow you to have as much control, I don't think that we want to ripe this out right now and test with this package, I can change the interfaces now and update the copied code if you and @pranavgaikwad feel like it is worth it.

File: jsonrpc2/backoff_handler.go (hunk 2 above)
Comment (shawn-hurley) [reply jsonrpc2/backoff_handler.go:145]: It happens after write, https://github.com/konveyor/analyzer-lsp/blob/main/jsonrpc2/jsonrpc2.go#L131-L133 so I think wrote still makes sense?

**Review by fabianvf — APPROVED** [review]
All makes sense, I hadn't dug into the interfaces so this was useful for me, sorry for the noise
