### PR TITLE
:sparkles:  Don't use full file paths for violations

### LINKED ISSUE #322: Full file paths for dependencies are irrelevant for the user
### Environment

- Fedora 36
- minikube v1.31.2 (--driver=kvm2 --memory=10g --cpus=3)
- Konveyor 0.3 alpha-2 with additional images:
  - ui_image_fqin: quay.io/ibolton/tackle2-ui:demo
  - hub_image_fqin: quay.io/jortel/tackle2-hub:demo
  - analyzer_fqin: quay.io/jortel/tackle2-addon-analyzer:demo
- [tackle-testapp](https://github.com/konveyor/tackle-testapp) application
- Analysis configuration: 
  - Source + Dependencies
  - cloud-readiness, linux
  - Application and internal dependencies only
  - No custom rules
  - No additional advanced options

### Description

Files in the affected files side drawer contain the full path to each file that contains incidents for the given issue. In the case of dependencies, this is displaying a long path to the location of the dependency JAR within the local .m2 repository available in the task pod. That information is completely irrelevant and potentially confusing for the user, that will only care about the JAR filename and the affected class/file within that JAR.

### How to reproduce

- Analyze tackle-test app with the configuration available in the Environment section.
- Go to the issues view, Single application, and filter by the tackle-testapp application.
- Select for example the _Java Mail API_ issue.
- Click on _View affected files_

### Expected result

JAR filenames alongside the path to the affected file within the JAR are displayed.

### Actual result

Full file paths are displayed for each file, not including the actual affected file inside the JAR as referenced in #321 

Screenshot from 2023-09-08 11-07-31

### PR DESCRIPTION
**Pull request by eemcmullan**
Closes #322

### CODE REVIEW

**Review by shawn-hurley — APPROVED** [review]
I think you have to fix the dependency test as well: 

https://github.com/konveyor/analyzer-lsp/actions/runs/8394658124/job/22992283193?pr=548#step:4:569

But other than that, this looks great and makes a ton of sense.

**Review by aufi — APPROVED** [review]
I agree with Shawn; need fix tests, otherwise looks great.

File: provider/internal/java/dependency.go [hunk 1]
```diff
@@ -411,7 +411,7 @@ func (p *javaServiceClient) parseDepString(dep, localRepoPath, pomPath string) (
 	fp := resolveDepFilepath(&d, p, group, artifact, localRepoPath)
 
 	d.Labels = addDepLabels(p.depToLabels, d.Name)
-	d.FileURIPrefix = fmt.Sprintf("file://%v", filepath.Dir(fp))
+	d.FileURIPrefix = fmt.Sprintf("file://%v", filepath.Dir(strings.TrimPrefix(fp, localRepoPath)))
```
Comment (pranavgaikwad) [inline provider/internal/java/dependency.go:414]: I don't think we should be doing this,

**Review by pranavgaikwad — CHANGES_REQUESTED** [review]

File: provider/internal/java/dependency.go (hunk 1 above)
Comment (shawn-hurley) [reply provider/internal/java/dependency.go:414]: why?

Comment (pranavgaikwad) [reply provider/internal/java/dependency.go:414]: this will break the dependency filtering logic, either we fix it in both places or don't change the fileURIPrefix at all, because this is mainly just an internal field

Comment (shawn-hurley) [reply provider/internal/java/dependency.go:414]: @eemcmullan this could be causing the failures too then maybe?

Comment (eemcmullan) [reply provider/internal/java/dependency.go:414]: Think so. Probably best then to trim this prefix in https://github.com/konveyor/analyzer-lsp/blob/main/cmd/analyzer/main.go#L423

File: cmd/analyzer/main.go [hunk 2]
```diff
@@ -437,10 +444,17 @@ func DependencyOutput(ctx context.Context, providers map[string]provider.Interna
 				continue
 			}
 			for u, ds := range deps {
+				var outputDepDag []konveyor.DepDAGItem
+				// trim m2 repo prefix for java deps
+				if name == "java" {
+					outputDepDag = trimDagItemPrefixes(ds)
```
Comment (pranavgaikwad) [inline cmd/analyzer/main.go:450]: sorry one small request...I think hardcoding for java provider here is unnecessary. there is no need to change prefix fields on dependencies as it isn't output to users in any incidents.

**Review by pranavgaikwad — CHANGES_REQUESTED** [review]
Sorry there's one small thing that concerns me, otherwise looking good. Thank you!

File: cmd/analyzer/main.go (hunk 2 above)
Comment (eemcmullan) [reply cmd/analyzer/main.go:450]: I think this is for the `--dep-output-file` for the user. Just checking for the java provider here as the trim() function it's calling is only used to trim the local m2 repo prefix. Wanted to avoid issue with other dep providers. However, if I'm off-track, please let me know.

Comment (pranavgaikwad) [reply cmd/analyzer/main.go:450]: I think it is fine to leave the prefixes as-is in the output @shawn-hurley wdyt?

**Review by pranavgaikwad — APPROVED** [review]
