### PR TITLE
:bug: use the capture groups if they are set

### LINKED ISSUE #219: Parameter interpolation not working properly sometimes
There are several rules with single or multiple `where` clauses which don't seem to be working properly. See for instance [this group of rules in the Failing rules doc](https://docs.google.com/spreadsheets/d/19_dL8ZiBu0ULghVdpLsx0zBhF8DcGnjwMwslIcQytoU/edit#gid=372217138&range=A85) or [this one](https://docs.google.com/spreadsheets/d/19_dL8ZiBu0ULghVdpLsx0zBhF8DcGnjwMwslIcQytoU/edit#gid=372217138&range=A30).

### LINKED ISSUE #258: We should probably only evaluate custom variables in code location's start and end range
Right now, we match the entire code snip which leaves some room for error if there's something else matching that's not actually just added for context in code snippet.

### PR DESCRIPTION
**Pull request by shawn-hurley**
Closes #258 
Closes #219

### CODE REVIEW

File: engine/engine.go [hunk 1]
```diff
@@ -423,34 +423,31 @@ func (r *ruleEngine) createViolation(ctx context.Context, conditionResponse Cond
...
 						m.Variables[cv.Name] = cv.DefaultValue
+						continue
+					case 1:
+						m.Variables[cv.Name] = strings.TrimSpace(match[0])
+						continue
+					case 2:
+						m.Variables[cv.Name] = strings.TrimSpace(match[1])
 					}
 				}
+				fmt.Printf("\n\noriginalCodSnip: %v\nVar: regex: %v --- %v --- %v", originalCodeSnip, cv.Pattern.String(), cv.Name, m.Variables[cv.Name])
```
Comment (pranavgaikwad) [inline engine/engine.go:450]: Remove or change to log?

**Review by pranavgaikwad — CHANGES_REQUESTED** [review]

**Review by pranavgaikwad — APPROVED** [review]
